@base = http://localhost:3003/api

@name = "Arttu Mäkinen"
@password = "salasana"

# @name login
POST {{base}}/login/
Content-Type: application/json

{
  "username": "arde2",
  "password": "konna"
}

###

POST {{base}}/users/
Content-Type: application/json

{
  "username": "arde2",
  "password": "konna",
  "name": "konna"
}

###

POST {{base}}/blogs/
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "title": "kommenttiblogi4",
  "author": "sdafdsadsafdsadsfdsa",
  "likes": 666,
  "url": "https://sieni.us"
}

###

POST {{base}}/api/testing/reset

###

POST http://localhost:3003/api/blogs/608591d01687e51cc9636798/comments
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}

{
  "comment": "moi xD",
  "this should not exist": true
}

